### ISSUE TITLE
Unable to set a route's regex_priority

### ISSUE THREAD

**Issue by andres-rojas** [kevholditch/gokong#21]
The `RouteRequest` struct doesn't accept a field to define the route's `regex_priority`:

- https://github.com/kevholditch/gokong/blob/master/routes.go#L12
- https://docs.konghq.com/0.13.x/proxy/#evaluation-order

**Comment by kevholditch** [comment]
@andres-rojas looking at the [documentation](https://docs.konghq.com/0.14.x/admin-api/#route-object) I don't believe this property is on the request? It comes back in the response and it is already on there or am I missing something?

**Comment by kevholditch** [comment]
@andres-rojas if you can indeed set this value then we need to have a test for this ie posting a route and setting the Regex priority and then checking the route that comes back has it set. We should also add a test to get a route that has this property set also. If you get that added then we will be covered and I’ll merge it in so you don’t need to maintain a custom fork. 

Out of interest are you using the kong terraform provided?

**Comment by andres-rojas** [comment]
Sounds good. I might not have time to do this before Monday, but I'll submit something soon for you to take a look at.

To answer your question: we're deploying Kong via the [community Helm chart](https://github.com/kubernetes/charts/tree/master/stable/kong) to a v1.10.x Kubernetes cluster. We are using Kops and Terraform for automating the deployment of the cluster.

I did see that you were also working on a Kong provider for Terraform, and I might end up giving that a try in the near future as well.

**Comment by kevholditch** [comment]
This is now fixed
