### ISSUE TITLE
object unmarshall of type []*string

### ISSUE THREAD

**Issue by pepito987** [kevholditch/gokong#23]
I'm using kong v0.10.2, I'm using `apis` as Resource and I'm facing an unmarshall error.
It looks like that if a list field like `hosts` when empty this will set to an actual empty object `{}`
 rather than empty list `[]`. 

After running PATCH on an apis resources: 
`{
	"hosts": []
}`

The GET will return:
`   { ...,
     "upstream_read_timeout": 60000,
    "upstream_send_timeout": 60000,
    "https_only": false,
    "hosts": {}
    }`
As you can see hosts is not an empty list but an empty object and terraform throw this during the import:
`could not find kong api: could not parse api get response, error: json: cannot unmarshal object into Go struct field Api.hosts of type []*string`

Also, I have the same error during a plan.

**Comment by kevholditch** [comment]
@pepito987 have you sorted this? noticed you have closed the issue

**Comment by pepito987** [comment]
No I actually did not, I opened the issue on `terraform-provider-kong`. I thought that that was a better place for it.

**Comment by pepito987** [comment]
Thanks a lot .. I have looked at the PR and noticed you apply the changes only to hosts. However, I think this is true for all the lists. I noticed the same happen with `uris` for instance

**Comment by kevholditch** [comment]
ok I'm going to have to work out a way of doing this generically as it is not going to scale to do it separately for all list fields
